#!/bin/bash

# correct /var/log permissions
sudo chmod g-w /var/log

# need to generate a password
sudo apt update
sudo apt install --assume-yes pwgen

MYSQL_ROOT_PW=$(pwgen --capitalize --numerals --secure --no-vowels 24 1)

DB_USER="slurm"
DB_ACCOUNTING="slurmaccounting"
DB_JOBCOMPLETION="slurmjobcompletion"

# create user and database entries for slurm + grant privilegeues
DB_USER_PW=$(pwgen --capitalize --numerals --secure --no-vowels 12 1)

DB_CONTAINER_NAME=slurm-mysql
DB_DIR=/srv/mysql/"$DB_CONTAINER_NAME"
DB_CONTAINER_PORT=3306

sudo mkdir -p "$DB_DIR"

sudo docker run --name "$DB_CONTAINER_NAME" --publish "$DB_CONTAINER_PORT":3306 -e MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PW" \
     -e MYSQL_DATABASE="$DB_ACCOUNTING" -e MYSQL_USER="$DB_USER" -e MYSQL_PASSWORD="$DB_USER_PW" \
     -v "$DB_DIR":/var/lib/mysql --restart=always -d mysql:5.6 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

sleep 60

sudo docker exec -it slurm-mysql mysql --password="$MYSQL_ROOT_PW" \
     --execute 'CREATE DATABASE '"$DB_JOBCOMPLETION"';
                GRANT ALL PRIVILEGES ON '"$DB_JOBCOMPLETION"'.* TO '"'$DB_USER'@'localhost'"' WITH GRANT OPTION;
                GRANT ALL PRIVILEGES ON '"$DB_JOBCOMPLETION"'.* TO '"'$DB_USER'@'%'"' WITH GRANT OPTION;
                FLUSH PRIVILEGES;'

sudo docker exec -it slurm-mysql mysql --password="$MYSQL_ROOT_PW" \
     --execute 'CREATE DATABASE '"$DB_JOBCOMPLETION"';
                GRANT ALL PRIVILEGES ON '"$DB_ACCOUNTING"'.* TO '"'$DB_USER'@'localhost'"' WITH GRANT OPTION;
                GRANT ALL PRIVILEGES ON '"$DB_ACCOUNTING"'.* TO '"'$DB_USER'@'%'"' WITH GRANT OPTION;
                FLUSH PRIVILEGES;'

sudo apt install --assume-yes munge mailutils

sudo apt install --assume-yes slurmdbd slurm-llnl

sudo create-munge-key -f

sudo service munge stop
sudo service munge start

SLURM_STATE_SAVE_LOCATION=/home2/slurmd

mkdir -p /etc/slurm-llnl
cat <<EOF | sudo tee /etc/slurm-llnl/slurm.conf
# slurm.conf file generated by configurator.html.
# Put this file on all nodes of your cluster.
# See the slurm.conf man page for more information.
#
ControlMachine=$HOSTNAME
#ControlAddr=
#BackupController=
#BackupAddr=
#
AuthType=auth/munge
#CheckpointType=checkpoint/none
CryptoType=crypto/munge
#DisableRootJobs=NO
#EnforcePartLimits=NO
#Epilog=
#EpilogSlurmctld=
#FirstJobId=1
#MaxJobId=999999
#GresTypes=
#GroupUpdateForce=0
#GroupUpdateTime=600
#JobCheckpointDir=/var/slurm/checkpoint
#JobCredentialPrivateKey=
#JobCredentialPublicCertificate=
#JobFileAppend=0
#JobRequeue=1
#JobSubmitPlugins=1
#KillOnBadExit=0
#LaunchType=launch/slurm
#Licenses=foo*4,bar
MailProg=/usr/bin/mail
#MaxJobCount=5000
#MaxStepCount=40000
#MaxTasksPerNode=128
MpiDefault=none
#MpiParams=ports=#-#
#PluginDir=
#PlugStackConfig=
#PrivateData=jobs
ProctrackType=proctrack/linuxproc
#Prolog=
#PrologFlags=
#PrologSlurmctld=
#PropagatePrioProcess=0
#PropagateResourceLimits=
#PropagateResourceLimitsExcept=
#RebootProgram=
ReturnToService=2
#SallocDefaultCommand=
SlurmctldPidFile=/var/run/slurm-llnl/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm-llnl/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/tmp/slurmd
SlurmUser=slurm
#SlurmdUser=root
#SrunEpilog=
#SrunProlog=
StateSaveLocation=$SLURM_STATE_SAVE_LOCATION
SwitchType=switch/none
#TaskEpilog=
TaskPlugin=task/none
#TaskPluginParam=
#TaskProlog=
#TopologyPlugin=topology/tree
#TmpFS=/tmp
#TrackWCKey=no
#TreeWidth=
#UnkillableStepProgram=
#UsePAM=0
#
#
# TIMERS
#BatchStartTimeout=10
#CompleteWait=0
#EpilogMsgTime=2000
#GetEnvTimeout=2
#HealthCheckInterval=0
#HealthCheckProgram=
InactiveLimit=0
KillWait=30
#MessageTimeout=10
#ResvOverRun=0
MinJobAge=300
#OverTimeLimit=0
SlurmctldTimeout=120
SlurmdTimeout=300
#UnkillableStepTimeout=60
#VSizeFactor=0
Waittime=0
#
#
# SCHEDULING
#DefMemPerCPU=0
FastSchedule=1
#MaxMemPerCPU=0
#SchedulerTimeSlice=30
SchedulerType=sched/backfill
SelectType=select/linear
#SelectTypeParameters=
#
#
# JOB PRIORITY
#PriorityFlags=
#PriorityType=priority/basic
#PriorityDecayHalfLife=
#PriorityCalcPeriod=
#PriorityFavorSmall=
#PriorityMaxAge=
#PriorityUsageResetPeriod=
#PriorityWeightAge=
#PriorityWeightFairshare=
#PriorityWeightJobSize=
#PriorityWeightPartition=
#PriorityWeightQOS=
#
#
# LOGGING AND ACCOUNTING
#AccountingStorageEnforce=0
AccountingStorageHost=127.0.0.1
AccountingStorageLoc=$DB_ACCOUNTING
AccountingStoragePass=$DB_USER_PW
#AccountingStoragePort=
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageUser=$DB_USER
AccountingStoreJobComment=YES
ClusterName=cctb-hpc
#DebugFlags=
JobCompHost=127.0.0.1
JobCompLoc=$DB_JOBCOMPLETION
JobCompPass=$DB_USER_PW
JobCompPort=$DB_CONTAINER_PORT
JobCompType=jobcomp/mysql
JobCompUser=$DB_USER
#JobContainerType=job_container/none
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/linux
SlurmctldDebug=3
#SlurmctldLogFile=
SlurmdDebug=3
#SlurmdLogFile=
#SlurmSchedLogFile=
#SlurmSchedLogLevel=
#
#
# POWER SAVE SUPPORT FOR IDLE NODES (optional)
#SuspendProgram=
#ResumeProgram=
#SuspendTimeout=
#ResumeTimeout=
#ResumeRate=
#SuspendExcNodes=
#SuspendExcParts=
#SuspendRate=
#SuspendTime=
#
#
# COMPUTE NODES
NodeName=saturn1 CPUs=80 RealMemory=500000 Sockets=4 CoresPerSocket=10 ThreadsPerCore=2 State=UNKNOWN
NodeName=saturn2 CPUs=80 RealMemory=500000 Sockets=4 CoresPerSocket=10 ThreadsPerCore=2 State=UNKNOWN
NodeName=jupiter CPUs=80 RealMemory=1000000 Sockets=4 CoresPerSocket=10 ThreadsPerCore=2 State=UNKNOWN
NodeName=uranus[1-3] CPUs=32 RealMemory=190000 Sockets=2 CoresPerSocket=16 ThreadsPerCore=1 State=UNKNOWN
NodeName=neptun1 CPUs=24 RealMemory=190000 Sockets=2 CoresPerSocket=6 ThreadsPerCore=2 State=UNKNOWN

PartitionName=cctb Nodes=saturn1,saturn2,jupiter,neptun1,uranus[1-3] Default=YES MaxTime=INFINITE State=UP
EOF

cat <<EOF | sudo tee /etc/slurm-llnl/slurmdbd.conf
#
# Example slurmdbd.conf file.
#
# See the slurmdbd.conf man page for more information.
#
# Archive info
#ArchiveJobs=yes
#ArchiveDir="/tmp"
#ArchiveSteps=yes
#ArchiveScript=
#JobPurge=12
#StepPurge=1
#
# Authentication info
AuthType=auth/munge
AuthInfo=/var/run/munge/munge.socket.2
#
# slurmDBD info
DbdAddr=localhost
DbdHost=localhost
#DbdPort=7031
SlurmUser=slurm
#MessageTimeout=300
DebugLevel=4
#DefaultQOS=normal,standby
LogFile=/var/log/slurm-llnl/slurmdbd.log
PidFile=/var/run/slurm-llnl/slurmdbd.pid
#PluginDir=/usr/lib/slurm
#PrivateData=accounts,users,usage,jobs
#TrackWCKey=yes
#
# Database info
StorageType=accounting_storage/mysql
StorageHost=127.0.0.1
StoragePort=$DB_CONTAINER_PORT
StoragePass=$DB_USER_PW
StorageUser=$DB_USER
StorageLoc=$DB_ACCOUNTING
EOF

sudo mkdir -p "$SLURM_STATE_SAVE_LOCATION"
chown slurm.slurm "$SLURM_STATE_SAVE_LOCATION"

# printing important information
MUNGE_KEY=$(sudo base64 /etc/munge/munge.key)

cat <<EOF


***************************************************************
*  Installation details                                       *
***************************************************************

Root password for MySQL database: '$MYSQL_ROOT_PW'

MySQL user for slurmctrl  : '$DB_USER'
Password for that user    : '$DB_USER_PW'
Database for accounting   : '$DB_ACCOUNTING'
Database for jobcompletion: '$DB_JOBCOMPLETION'

Munge key '/etc/munge/munge.key' 64base encoded:
$MUNGE_KEY


EOF

sudo service start slurmdbd
sudo service start slurmctld
